name: rust release action
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: release
        uses: lxl66566/rust-simple-release@main
        with:
          targets: |
            x86_64-pc-windows-msvc

          token: ${{ secrets.GH_TOKEN }}
